language: java

env:
  global:
    - SURGE_LOGIN=rlicchi@scmgroup.com
    - secure: "JnkuS6QCbn1xUDwBMG40DURATCkchqqHB5v6s+4G2mVPOvgrf3I1awtWIxmDldMW+LYOI/dYf7Sx0ff1pRsgd3au443l4sUgx8F3K81+r+AT1H55zojwBbMXyWZqtkU+5fHIwnk2zzJrKIkfWf7TIa5QttZP9BKjLnEQbp+GdhW1mn1vwX8T1q0B3qH9DHgw4Q+v8pMrZPSvCZxHAWzYv9XsXGm4Z85hmRb+H7btDbk7jmDLVVLZb5piE0d4fZAiyGZixfHvcz0v2A0se04hrtw8Wt8jMcgEjjipacCILC/7uo5Zar9XgZIbl55XSa4F6cTcLveDqwEANFlfPA5LczFQp13e2FKayunolsO46FpMOAgkTrk/O0qFAkSBoeyTnpjt8nXAT4dIVMxSxU6phmy02e+q963f+WCXsiFcX0rZeoQVmuUxK6g0GnOafBR7twQ3t6tHqahEzyL6mccn0d3rk1wzjgrNOTK63d0qF9l4QYAjEn5W3zXSSWF7ubiBAvUYBTuDcdntfmvoc9PDD6OPZ5n5ySUWCw18QSpPCfwcHFpzXOvtYdc5hJzlwXHvNAvDXjTx1mN/FUfKZYAul8PNrLxxzvq3EItLFGgP46cM9VKIeIzB+mmA1vnr9ky3ZoUDnozDuyQ4Ch6fxY+t8swlJSFegE2A+aO6/FUkUHk="
# Disable Travis install phase
install: true

# Execute our custom build
script:
  - ./gradlew clean buildDashboard
    
deploy:
  provider: surge
  project: build/report/
  domain: 2018-scm-reports-richi.surge.sh
  skip_cleanup: true
  on:
    all_branches: true